const htmlTagsCategorized: Record<string, string[]> = {
  Structure: [
    "html",
    "head",
    "body",
    "main",
    "header",
    "footer",
    "section",
    "article",
    "aside",
    "nav",
  ],
  Metadata: ["title", "meta", "link", "style", "base", "script", "noscript"],
  "Text Content": ["h1", "h2", "h3", "h4", "h5", "h6", "p", "span", "div", "br", "hr", "pre"],
  "Inline Text Semantics": [
    "strong",
    "b",
    "em",
    "i",
    "u",
    "small",
    "mark",
    "abbr",
    "cite",
    "code",
    "kbd",
    "sub",
    "sup",
    "time",
    "var",
  ],
  "Links & Navigation": ["a", "nav"],
  Media: ["img", "audio", "video", "source", "track", "picture", "map", "area"],
  "Embedded Content": ["iframe", "embed", "object", "param", "canvas", "svg"],
  Forms: [
    "form",
    "input",
    "textarea",
    "select",
    "option",
    "optgroup",
    "label",
    "fieldset",
    "legend",
    "button",
    "datalist",
    "output",
    "meter",
    "progress",
  ],
  Tables: ["table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption", "colgroup", "col"],
  Scripting: ["script", "noscript", "template", "canvas"],
  "Interactive Elements": ["details", "summary", "dialog", "menu", "menuitem"],
  "Web Components": ["slot", "template"],
}

export default htmlTagsCategorized
